Add basic structure html
J2ZROMERO/Hello_world_project pull request #2
Opened 2022-08-17 14:29 UTC by J2ZROMERO

actions realized in this branch:
- add index.html
- add style.css
- add gitignore file
- file README.md modified
- add test.md (untrack by .gitignore)
- add liter to project

2022-08-17 14:36 UTC, ShahierNashaat requested changes
Hi @J2ZROMERO, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️

## Required Changes ♻️
- [ ] Kindly be noticed that Linter should be set up correctly for this repository.
- [ ] Also notice that the Linter result should be green. AKA: Linter should report NO errors.
- [ ] Also notice that there are 2 files committed: an .html and .css file. The content of those files is not relevant to this project.
- [ ] Also notice that there is a .gitignore file listing `test.md` file and `node_modules` directory.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 14:36 UTC, ShahierNashaat commented on README.md
> +# Hello_world_project
- [ ] Kindly be noticed that the README file should be descriptive. AKA: Microverse [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) should be used.

2022-08-17 15:45 UTC, J2ZROMERO commented on README.md
> +# Hello_world_project
Hi, many thanks for reviewing my code, I have some doubts: how I have to apply that changes  I need to  rewrite that changes in Github or in my computer

2022-08-17 15:50 UTC, ShahierNashaat commented on README.md
> +# Hello_world_project
On your computer

2022-08-17 20:23 UTC, J2ZROMERO commented on README.md
> +# Hello_world_project
ok, I am facing issues when I did git push previous deliver the project, I notice that I had wrong some files so I dont know how to solve the issues then I did click on a revert pull request and now I can't update:
- because the branch on GitHub now is revert-1-add_basic_structure
- and the same project on my computer just has add_basic_structure like the name  of the branch
- so when I write a push on my computer, immediately git hub takes this push like a new pull request
- I had cloned again the project looks like that I have add a new pull request again
I would appreciate your help
![commit1](https://user-images.githubusercontent.com/63516282/185235788-410dbce9-927c-4f6f-a281-0a9ed83470df.png)
![git2](https://user-images.githubusercontent.com/63516282/185235791-f5e9ae59-941c-41a2-bdf9-581444eb2dfe.png)

2022-08-17 20:54 UTC, ShahierNashaat commented on README.md
> +# Hello_world_project
Ok then make the changes on GitHub

2022-08-17 20:58 UTC, J2ZROMERO commented on README.md
> +# Hello_world_project
so, I have to create a new pull request?

2022-08-17 20:59 UTC, ShahierNashaat commented on README.md
> +# Hello_world_project
No there is no need to create a new pull request

2022-08-17 21:02 UTC, J2ZROMERO commented on README.md
> +# Hello_world_project
what I have to do?

2022-08-17 21:05 UTC, J2ZROMERO commented on README.md
> +# Hello_world_project
![2022-08-17_16h05_13](https://user-images.githubusercontent.com/63516282/185242902-abf77c4a-37f5-4f8e-bf45-8764bcd894be.png)

2022-08-17 21:56 UTC, GzimAsani requested changes
### Hello @J2ZROMERO            :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job implementing almost all the previous reviewer requirements:+1: 
 
 ## Required Changes 

- [ ] Kindly use Microverse [template](https://github.com/microverseinc/readme-template) as it would make your readme file look more professional



 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 22:01 UTC, J2ZROMERO commented
Hi, I don't understand that step, just I have to copy and paste the template  or I have to rewrite the file with my data

2022-08-17 22:04 UTC, GzimAsani commented
> Hi, I don't understand that step, just I have to copy and paste the template or I have to rewrite the file with my data

Hi, you need to rewrite it your data, but take a step closer and add the semantic look as well, which makes your readme file look prettier and more professional

2022-08-17 22:24 UTC, J2ZROMERO commented
ok, just sorry for my persistence, what do you mean with semantic

2022-08-18 13:56 UTC, 1GORDON requested changes
##
## Hi @J2ZROMERO ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] As stated by the previous reviewer, kindly add the missing [linter files](https://github.com/microverseinc/linters-config/tree/master/html-css). The two missing files should be added to your root directory. These files are `.hintrc` file and `.stylelintrc.json` file. You can find these files in the link I have put in this comment.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 13:56 UTC, 1GORDON commented on README.md
> +- GitHub: [@githubhandle](@https://github.com/J2ZROMERO)
Great job @J2ZROMERO 🤝

- [ ] [Optional]Kindly remove` @` in your Github handle. This will allow for your link to be active.

2022-08-18 15:53 UTC, Ugboaja-Uchechi approved these changes
Hi @J2ZROMERO,

## Status: APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 
- Great job with your design and functionalities 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 16:13 UTC, merged